basePath: /
definitions:
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  dto.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  dto.RegisterTraderRequest:
    properties:
      login:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  dto.RegisterTraderResponse:
    type: object
info:
  contact: {}
  description: API for internal admin panel
  title: Admin Service API
  version: "1.0"
paths:
  /admin/traders/register:
    post:
      consumes:
      - application/json
      description: Register new trader team by credentials
      parameters:
      - description: trader credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterTraderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.RegisterTraderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Register new trader team
      tags:
      - traders
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and receive JWT
      parameters:
      - description: user creds
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Login user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
